# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

language: go
go:
  - 1.10
go_import_path:  github.com/hyperledger/fabric
sudo: required

services:
  - docker

env:
  - TEST_TARGET=unit-tests
  - TEST_TARGET=hbmpc-tests-with-deps
  - TEST_TARGET=integration-test

script: make $TEST_TARGET
